# Generated by Django 6.0.2 on 2026-02-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_project_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_Created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
