# Generated by Django 6.0.2 on 2026-02-07 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_project_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='date_Created',
            new_name='date_created',
        ),
    ]
